config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
 resources :posts do
 	resources :comments
 end

 root "posts#index"

 get '/about', to: 'pages#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, :dependent => :destroy
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_comment, only: [:create, :destroy]

	def create		
		@comment = @post.comments.create(comment_params)

		redirect_to post_path(@post)		
	end

	def destroy
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

		private

		def find_comment
			@post = Post.find(params[:post_id])
		end 

		def comment_params
			params.require(:comment).permit(:name, :body)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about 
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [ :show, :edit, :update, :destroy ]
	before_action :authenticate_user!, except: [ :index, :show ]

	def index
		@posts = Post.all.order('created_at DESC')
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'new'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

		private 

			def find_post
				@post = Post.find(params[:id])
			end

			def post_params
			  params.require(:post).permit(:title, :body)
			end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
%div{ :class => "comment clearfix" }
	.comment_content
		%p{ :class => "comment_name"}= comment.name
		%p{ :class => "comment_body"}= comment.body
		%p{ :class => "comment_title"} #{ time_ago_in_words(comment.created_at) } Ago

		- if user_signed_in?
			%p= link_to 'Delete', [ comment.post, comment ], method: :delete, class: "button", data: { confirm: 'Are you sure' }

app/views/comments/_form.html.haml
= form_for([@post, @post.comments.build]) do |f|

	%p= f.label :name
	%p= f.text_field :name

	%p= f.label :body
	%p= f.text_area :body

	%br

	%p
		=	f.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tumblr
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag			'application', 'https://fonts.googleapis.com/css?family=Patua+One:400,700'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags

  %body
    #sidebar
      %ul
        %li= link_to "Tumblr", root_path, :class => "category" 
        %li= link_to "Posts", root_path
        %li= link_to "About", about_path

      -if !user_signed_in?
        %p{ :class => "sign_in"}= link_to "User Login", new_user_session_path 

    #main_content
      #header
        - if current_page?(root_path)
          %p Post Feed
        - elsif current_page?(about_path)
          %p My Site 
        - else 
          = link_to "Back to Post Feed", root_path


        -if user_signed_in?
          .buttons
            = link_to "Make Post", new_post_path, :class => "button"
            = link_to "Log Out", destroy_user_session_path, method: :delete, :class => "button"

      - flash.each do |name, msg|
        = content_tag(:div, msg, class: "alert")

      = yield

app/views/pages/about.html.haml
#page_wrapper
	#profile_image
		= image_tag 'profile.png'

	#content
		%h1 Its'. Mr. Stick Figure

		%p es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.

app/views/posts/_form.html.haml
=form_for @post do |f|
	- if @post.errors.any?
		#erros
			%h2 #{ pluralize( @post.errors.count, "erros" ) } stopped this post from saving
			%ul 
				- @post.errors.full_messages.each do |msg|
					%li= msg
	%p
		=f.label :title
		%br
		=f.text_field :title

	%p
		=f.label :body
		%br
		=f.text_area :body

	%p
		=f.submit

app/views/posts/edit.html.haml
#page_wrapper
	%h1 Fix Post

	= render 'form'

app/views/posts/index.html.haml
- @posts.each do |post|
	.post_wrapper
		.title
			%h2= link_to post.title, post

		.body
			%p= truncate( post.body, length:100 )

		.date
			%p
				= time_ago_in_words( post.created_at )
				ago

app/views/posts/new.html.haml
#page_wrapper
	%h1 Make Something

	=form_for :pots, url: posts_path do |f|
		- if @post.errors.any?
			#erros
				%h2 #{ pluralize( @post.errors.count, "erros" ) } stopped this post from saving
				%ul 
					- @post.errors.full_messages.each do |msg|
						%li= msg
		%p
			=f.label :title
			%br
			=f.text_field :title

		%p
			=f.label :body
			%br
			=f.text_area :body

		%p
			=f.submit

app/views/posts/show.html.haml
#post_content
	%h1{ :class => "title" }= @post.title

	%p.date 
		Submitted 
		= time_ago_in_words(@post.created_at)
		ago 
		- if user_signed_in?
			= link_to 'Edit', edit_post_path(@post)  
			| 
			= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure'} 


	%p{ :class => "body" }= @post.body

	#comments
		%h2 #{ @post.comments.count } Comments
		= render @post.comments
		%h3 Join Discussion:
		= render "comments/form"